spring:
  profiles:
    active: local
    include: logging
  boot:
    admin:
      client:
        username: ${SPRING_BOOT_ADMIN_USERNAME}
        password: ${SPRING_BOOT_ADMIN_PASSWORD}
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

