management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  boot:
    admin:
      client:
        username: ${SPRING_BOOT_ADMIN_USERNAME}
        password: ${SPRING_BOOT_ADMIN_PASSWORD}
        instance:
          metadata:
            user:
              name: ${SPRING_BOOT_ADMIN_USERNAME}
              password: ${SPRING_BOOT_ADMIN_PASSWORD}
